### Home (restricted route)
GET http://localhost:8080/
content-Type: application/json

### Register
POST http://localhost:8080/auth/register
content-Type: application/json

{
    "username": "ward",
    "password": "String",
    "email": "ward.test7.com"
}

### Login
POST http://localhost:8080/auth/login
content-Type: application/json

{
    "email": "ward.test7.com",
    "password": "ward"
}

### Logout
POST http://localhost:8080/auth/logout

### Get User
GET http://localhost:8080/auth/me
content-Type: application/json

### Get Workouts
GET http://localhost:8080/workouts/
content-Type: application/json

### POST Workouts
POST http://localhost:8080/workouts/
content-Type: application/json

{
    "name": "fuck today",
    "type": "Cardio",
    "description":"lorem",
    "duration":12.12
}

### Get Workout
GET http://localhost:8080/workouts/33
content-Type: application/json


### Get LastSevenDaysWorkouts
GET http://localhost:8080/workouts/lastSevenDaysWorkouts
content-Type: application/json


### Reset Password
POST http://localhost:8080/passwordReset    
content-Type: application/json

{
    "email": "ward.test7.com"
    
}
### Reset Password

POST http://localhost:8080/passwordReset/8/bbd8f97ebccc707105fd63a5d56330aa6076270d79c6c73a162af7ebb371cbf1
content-Type: application/json

{
    "password": "ward"
    
}